### ISSUE TITLE
Include helper not working

### ISSUE THREAD

**Issue by haustraliaer** [assemble/assemble-boilerplate-markdown#1]
I can't seem to compile using `grunt assemble` as I get the following error:

```
Assembling dest/markdown-block-2.html ERROR
Warning: Could not find property 'include' Use --force to continue
```

This is troubling, as I downloaded the boilerplate specifically to figure out how the handlebars-helper library worked with assemble.

Could you shed some light on this?

**Comment by jonschlinkert** [comment]
@haustraliaer btw, you probably already have it building. but the link was wrong for the demo for this boilerplate, this is the correct one if you want to see it live http://assemble.github.io/boilerplate-markdown
